# `jj-ci install` — print (or write) the two aliases jj needs.
#
# jj refuses to load command aliases from --config, --config-file or -R:
# "Command aliases cannot be loaded from …". So they have to be in a real
# config file, and the user-level one is the only place that makes them
# available in every repository.
#
# On a machine where that file is generated — home-manager, chezmoi, any
# dotfile manager — writing to it is either impossible or gets reverted on the
# next rebuild. So printing is the default, and --write is the exception.

const LIB = path self "../lib"
use $"($LIB)/log.nu" *

export def invoke [
  bin: string # absolute path to bin/jj-ci
  format: string # toml | nix | both
  on_path: bool # emit the bare name instead of an absolute path
  write: bool
]: nothing -> int {
  let cmd = (if $on_path { "jj-ci" } else { $bin })

  if $write {
    return (write-user-config $cmd)
  }

  if $format in ["toml" "both"] { print (toml-block $cmd) }
  if $format == "both" { print "" }
  if $format in ["nix" "both"] { print (nix-block $cmd) }
  0
}

def toml-block [cmd: string]: nothing -> string {
  r#'
# ~/.config/jj/config.toml
[aliases]
ci = ["util", "exec", "--", "@CMD@", "ci"]
push = ["util", "exec", "--", "@CMD@", "push"]'#
  | str trim --left
  | str replace --all "@CMD@" $cmd
}

def nix-block [cmd: string]: nothing -> string {
  r#'
# home-manager
programs.jujutsu.settings.aliases = {
  ci = [ "util" "exec" "--" "@CMD@" "ci" ];
  push = [ "util" "exec" "--" "@CMD@" "push" ];
};

# Nushell completions for those two aliases. jj generates its own the same way,
# and it cannot know about aliases, so this is a second file beside it.
home.activation.jjCiNushellCompletions = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
  mkdir -p "$HOME/.config/nushell/completions"
  @CMD@ completions nushell > "$HOME/.config/nushell/completions/jj-ci.nu"
'';

# …and, beside the line that sources jj.nu:
#   source ~/.config/nushell/completions/jj-ci.nu'#
  | str trim --left
  | str replace --all "@CMD@" $cmd
}

def write-user-config [cmd: string]: nothing -> int {
  let target = (^jj config path --user | str trim)
  if ($target | path type) == "symlink" {
    err $"($target) is a symlink — it is generated by a dotfile manager, and writing here would be lost."
    info "run `jj-ci install --format nix` and put the result in your configuration instead"
    return 1
  }
  for sub in ["ci" "push"] {
    let definition = (
      r#'["util", "exec", "--", "@CMD@", "@SUB@"]'#
      | str replace --all "@CMD@" $cmd
      | str replace --all "@SUB@" $sub
    )
    let r = (^jj config set --user $"aliases.($sub)" $definition | complete)
    if $r.exit_code != 0 {
      err ($r.stderr | str trim)
      return 1
    }
  }
  print $"(ansi green)✓(ansi reset) aliases ci and push written to ($target)"
  info "jj push now gates every repository that has a .jj-ci.toml"
  0
}
